// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Create(arg1:domain.Customer):Promise<domain.Customer>;

export function Delete(arg1:domain.Customer):Promise<void>;

export function FindAll():Promise<Array<domain.Customer>>;

export function FindOne(arg1:string):Promise<domain.Customer>;

export function Update(arg1:domain.Customer):Promise<domain.Customer>;
