// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['controllers']['CustomerController']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['controllers']['CustomerController']['Delete'](arg1);
}

export function FindAll() {
  return window['go']['controllers']['CustomerController']['FindAll']();
}

export function FindOne(arg1) {
  return window['go']['controllers']['CustomerController']['FindOne'](arg1);
}

export function Update(arg1) {
  return window['go']['controllers']['CustomerController']['Update'](arg1);
}
